### ISSUE TITLE
Can we use maven replace the ant +ivy, or enhance the document with how to import project to a IDE

### ISSUE THREAD

**Issue by kylinsoong** [jesperpedersen/fungal#2]
If switch to use maven, it will be more compatible with other open source and easy to distribute. 
Also, the current Developer Guide lack the content of importing project to a IED, eclipse, etc.
Can you thought this as a enhancement?

**Comment by jesperpedersen** [comment]
Maven artifacts are deployed to http://jesperpedersen.github.com/fungal/maven2

Maven won't be used as a build environment, but feel free to contribute to the developer guide
